mode: deployment

image:
  repository: "otel/opentelemetry-collector-k8s"

resources:
  limits:
    cpu: 100m
    memory: 200M

config:
  service:
    telemetry:
      metrics:
        address: example.com:8888
